// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imlThrift.proto

package iml;

public final class ImlThrift {
    private ImlThrift() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
	registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor internal_static_AuthMessage_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_AuthMessage_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_Reject_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_Reject_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_TextMessage_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_TextMessage_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
	return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
	java.lang.String[] descriptorData = { "\n\017imlThrift.proto\"1\n\013AuthMessage\022\020\n\010user"
		+ "name\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"\030\n\006Reject\022\016"
		+ "\n\006reason\030\001 \001(\t\"1\n\013TextMessage\022\017\n\007message"
		+ "\030\001 \001(\t\022\021\n\ttimestamp\030\002 \001(\003B\007\n\003imlP\001b\006prot" + "o3" };
	descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
		new com.google.protobuf.Descriptors.FileDescriptor[] {});
	internal_static_AuthMessage_descriptor = getDescriptor().getMessageTypes().get(0);
	internal_static_AuthMessage_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
		internal_static_AuthMessage_descriptor, new java.lang.String[] { "Username", "Password", });
	internal_static_Reject_descriptor = getDescriptor().getMessageTypes().get(1);
	internal_static_Reject_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
		internal_static_Reject_descriptor, new java.lang.String[] { "Reason", });
	internal_static_TextMessage_descriptor = getDescriptor().getMessageTypes().get(2);
	internal_static_TextMessage_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
		internal_static_TextMessage_descriptor, new java.lang.String[] { "Message", "Timestamp", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
