// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imlThrift.proto

package iml;

/**
 * Protobuf type {@code Reject}
 */
public final class Reject extends com.google.protobuf.GeneratedMessageV3 implements
	// @@protoc_insertion_point(message_implements:Reject)
	RejectOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Reject.newBuilder() to construct.
    private Reject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
	super(builder);
    }

    private Reject() {
	reason_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
	return new Reject();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
	return this.unknownFields;
    }

    private Reject(com.google.protobuf.CodedInputStream input,
	    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
	    throws com.google.protobuf.InvalidProtocolBufferException {
	this();
	if (extensionRegistry == null) {
	    throw new java.lang.NullPointerException();
	}
	com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
	try {
	    boolean done = false;
	    while (!done) {
		int tag = input.readTag();
		switch (tag) {
		case 0:
		    done = true;
		    break;
		case 10: {
		    java.lang.String s = input.readStringRequireUtf8();

		    reason_ = s;
		    break;
		}
		default: {
		    if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
			done = true;
		    }
		    break;
		}
		}
	    }
	} catch (com.google.protobuf.InvalidProtocolBufferException e) {
	    throw e.setUnfinishedMessage(this);
	} catch (java.io.IOException e) {
	    throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
	} finally {
	    this.unknownFields = unknownFields.build();
	    makeExtensionsImmutable();
	}
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
	return iml.ImlThrift.internal_static_Reject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
	return iml.ImlThrift.internal_static_Reject_fieldAccessorTable.ensureFieldAccessorsInitialized(iml.Reject.class,
		iml.Reject.Builder.class);
    }

    public static final int REASON_FIELD_NUMBER = 1;
    private volatile java.lang.Object reason_;

    /**
     * <code>string reason = 1;</code>
     * 
     * @return The reason.
     */
    @java.lang.Override
    public java.lang.String getReason() {
	java.lang.Object ref = reason_;
	if (ref instanceof java.lang.String) {
	    return (java.lang.String) ref;
	} else {
	    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
	    java.lang.String s = bs.toStringUtf8();
	    reason_ = s;
	    return s;
	}
    }

    /**
     * <code>string reason = 1;</code>
     * 
     * @return The bytes for reason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getReasonBytes() {
	java.lang.Object ref = reason_;
	if (ref instanceof java.lang.String) {
	    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
	    reason_ = b;
	    return b;
	} else {
	    return (com.google.protobuf.ByteString) ref;
	}
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
	byte isInitialized = memoizedIsInitialized;
	if (isInitialized == 1)
	    return true;
	if (isInitialized == 0)
	    return false;

	memoizedIsInitialized = 1;
	return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
	if (!getReasonBytes().isEmpty()) {
	    com.google.protobuf.GeneratedMessageV3.writeString(output, 1, reason_);
	}
	unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
	int size = memoizedSize;
	if (size != -1)
	    return size;

	size = 0;
	if (!getReasonBytes().isEmpty()) {
	    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, reason_);
	}
	size += unknownFields.getSerializedSize();
	memoizedSize = size;
	return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
	if (obj == this) {
	    return true;
	}
	if (!(obj instanceof iml.Reject)) {
	    return super.equals(obj);
	}
	iml.Reject other = (iml.Reject) obj;

	if (!getReason().equals(other.getReason()))
	    return false;
	if (!unknownFields.equals(other.unknownFields))
	    return false;
	return true;
    }

    @java.lang.Override
    public int hashCode() {
	if (memoizedHashCode != 0) {
	    return memoizedHashCode;
	}
	int hash = 41;
	hash = (19 * hash) + getDescriptor().hashCode();
	hash = (37 * hash) + REASON_FIELD_NUMBER;
	hash = (53 * hash) + getReason().hashCode();
	hash = (29 * hash) + unknownFields.hashCode();
	memoizedHashCode = hash;
	return hash;
    }

    public static iml.Reject parseFrom(java.nio.ByteBuffer data)
	    throws com.google.protobuf.InvalidProtocolBufferException {
	return PARSER.parseFrom(data);
    }

    public static iml.Reject parseFrom(java.nio.ByteBuffer data,
	    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
	    throws com.google.protobuf.InvalidProtocolBufferException {
	return PARSER.parseFrom(data, extensionRegistry);
    }

    public static iml.Reject parseFrom(com.google.protobuf.ByteString data)
	    throws com.google.protobuf.InvalidProtocolBufferException {
	return PARSER.parseFrom(data);
    }

    public static iml.Reject parseFrom(com.google.protobuf.ByteString data,
	    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
	    throws com.google.protobuf.InvalidProtocolBufferException {
	return PARSER.parseFrom(data, extensionRegistry);
    }

    public static iml.Reject parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
	return PARSER.parseFrom(data);
    }

    public static iml.Reject parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
	    throws com.google.protobuf.InvalidProtocolBufferException {
	return PARSER.parseFrom(data, extensionRegistry);
    }

    public static iml.Reject parseFrom(java.io.InputStream input) throws java.io.IOException {
	return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static iml.Reject parseFrom(java.io.InputStream input,
	    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
	return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static iml.Reject parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
	return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static iml.Reject parseDelimitedFrom(java.io.InputStream input,
	    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
	return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static iml.Reject parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
	return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static iml.Reject parseFrom(com.google.protobuf.CodedInputStream input,
	    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
	return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
	return newBuilder();
    }

    public static Builder newBuilder() {
	return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(iml.Reject prototype) {
	return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
	return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
	Builder builder = new Builder(parent);
	return builder;
    }

    /**
     * Protobuf type {@code Reject}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
	    // @@protoc_insertion_point(builder_implements:Reject)
	    iml.RejectOrBuilder {
	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
	    return iml.ImlThrift.internal_static_Reject_descriptor;
	}

	@java.lang.Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
	    return iml.ImlThrift.internal_static_Reject_fieldAccessorTable
		    .ensureFieldAccessorsInitialized(iml.Reject.class, iml.Reject.Builder.class);
	}

	// Construct using iml.Reject.newBuilder()
	private Builder() {
	    maybeForceBuilderInitialization();
	}

	private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
	    super(parent);
	    maybeForceBuilderInitialization();
	}

	private void maybeForceBuilderInitialization() {
	    if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
	    }
	}

	@java.lang.Override
	public Builder clear() {
	    super.clear();
	    reason_ = "";

	    return this;
	}

	@java.lang.Override
	public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
	    return iml.ImlThrift.internal_static_Reject_descriptor;
	}

	@java.lang.Override
	public iml.Reject getDefaultInstanceForType() {
	    return iml.Reject.getDefaultInstance();
	}

	@java.lang.Override
	public iml.Reject build() {
	    iml.Reject result = buildPartial();
	    if (!result.isInitialized()) {
		throw newUninitializedMessageException(result);
	    }
	    return result;
	}

	@java.lang.Override
	public iml.Reject buildPartial() {
	    iml.Reject result = new iml.Reject(this);
	    result.reason_ = reason_;
	    onBuilt();
	    return result;
	}

	@java.lang.Override
	public Builder clone() {
	    return super.clone();
	}

	@java.lang.Override
	public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
	    return super.setField(field, value);
	}

	@java.lang.Override
	public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
	    return super.clearField(field);
	}

	@java.lang.Override
	public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
	    return super.clearOneof(oneof);
	}

	@java.lang.Override
	public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
		java.lang.Object value) {
	    return super.setRepeatedField(field, index, value);
	}

	@java.lang.Override
	public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
	    return super.addRepeatedField(field, value);
	}

	@java.lang.Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
	    if (other instanceof iml.Reject) {
		return mergeFrom((iml.Reject) other);
	    } else {
		super.mergeFrom(other);
		return this;
	    }
	}

	public Builder mergeFrom(iml.Reject other) {
	    if (other == iml.Reject.getDefaultInstance())
		return this;
	    if (!other.getReason().isEmpty()) {
		reason_ = other.reason_;
		onChanged();
	    }
	    this.mergeUnknownFields(other.unknownFields);
	    onChanged();
	    return this;
	}

	@java.lang.Override
	public final boolean isInitialized() {
	    return true;
	}

	@java.lang.Override
	public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
		com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
	    iml.Reject parsedMessage = null;
	    try {
		parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
	    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
		parsedMessage = (iml.Reject) e.getUnfinishedMessage();
		throw e.unwrapIOException();
	    } finally {
		if (parsedMessage != null) {
		    mergeFrom(parsedMessage);
		}
	    }
	    return this;
	}

	private java.lang.Object reason_ = "";

	/**
	 * <code>string reason = 1;</code>
	 * 
	 * @return The reason.
	 */
	public java.lang.String getReason() {
	    java.lang.Object ref = reason_;
	    if (!(ref instanceof java.lang.String)) {
		com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
		java.lang.String s = bs.toStringUtf8();
		reason_ = s;
		return s;
	    } else {
		return (java.lang.String) ref;
	    }
	}

	/**
	 * <code>string reason = 1;</code>
	 * 
	 * @return The bytes for reason.
	 */
	public com.google.protobuf.ByteString getReasonBytes() {
	    java.lang.Object ref = reason_;
	    if (ref instanceof String) {
		com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
		reason_ = b;
		return b;
	    } else {
		return (com.google.protobuf.ByteString) ref;
	    }
	}

	/**
	 * <code>string reason = 1;</code>
	 * 
	 * @param value The reason to set.
	 * @return This builder for chaining.
	 */
	public Builder setReason(java.lang.String value) {
	    if (value == null) {
		throw new NullPointerException();
	    }

	    reason_ = value;
	    onChanged();
	    return this;
	}

	/**
	 * <code>string reason = 1;</code>
	 * 
	 * @return This builder for chaining.
	 */
	public Builder clearReason() {

	    reason_ = getDefaultInstance().getReason();
	    onChanged();
	    return this;
	}

	/**
	 * <code>string reason = 1;</code>
	 * 
	 * @param value The bytes for reason to set.
	 * @return This builder for chaining.
	 */
	public Builder setReasonBytes(com.google.protobuf.ByteString value) {
	    if (value == null) {
		throw new NullPointerException();
	    }
	    checkByteStringIsUtf8(value);

	    reason_ = value;
	    onChanged();
	    return this;
	}

	@java.lang.Override
	public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
	    return super.setUnknownFields(unknownFields);
	}

	@java.lang.Override
	public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
	    return super.mergeUnknownFields(unknownFields);
	}

	// @@protoc_insertion_point(builder_scope:Reject)
    }

    // @@protoc_insertion_point(class_scope:Reject)
    private static final iml.Reject DEFAULT_INSTANCE;
    static {
	DEFAULT_INSTANCE = new iml.Reject();
    }

    public static iml.Reject getDefaultInstance() {
	return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Reject> PARSER = new com.google.protobuf.AbstractParser<Reject>() {
	@java.lang.Override
	public Reject parsePartialFrom(com.google.protobuf.CodedInputStream input,
		com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		throws com.google.protobuf.InvalidProtocolBufferException {
	    return new Reject(input, extensionRegistry);
	}
    };

    public static com.google.protobuf.Parser<Reject> parser() {
	return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Reject> getParserForType() {
	return PARSER;
    }

    @java.lang.Override
    public iml.Reject getDefaultInstanceForType() {
	return DEFAULT_INSTANCE;
    }

}
