// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imlThrift.proto

package iml;

public interface RejectOrBuilder extends
	// @@protoc_insertion_point(interface_extends:Reject)
	com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string reason = 1;</code>
     * 
     * @return The reason.
     */
    java.lang.String getReason();

    /**
     * <code>string reason = 1;</code>
     * 
     * @return The bytes for reason.
     */
    com.google.protobuf.ByteString getReasonBytes();
}
