// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imlThrift.proto

package iml;

public interface TextMessageOrBuilder extends
	// @@protoc_insertion_point(interface_extends:TextMessage)
	com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     * 
     * @return The message.
     */
    java.lang.String getMessage();

    /**
     * <code>string message = 1;</code>
     * 
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString getMessageBytes();

    /**
     * <code>int64 timestamp = 2;</code>
     * 
     * @return The timestamp.
     */
    long getTimestamp();
}
