// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imlThrift.proto

package iml;

/**
 * Protobuf type {@code TextMessage}
 */
public final class TextMessage extends com.google.protobuf.GeneratedMessageV3 implements
	// @@protoc_insertion_point(message_implements:TextMessage)
	TextMessageOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use TextMessage.newBuilder() to construct.
    private TextMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
	super(builder);
    }

    private TextMessage() {
	message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
	return new TextMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
	return this.unknownFields;
    }

    private TextMessage(com.google.protobuf.CodedInputStream input,
	    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
	    throws com.google.protobuf.InvalidProtocolBufferException {
	this();
	if (extensionRegistry == null) {
	    throw new java.lang.NullPointerException();
	}
	com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
	try {
	    boolean done = false;
	    while (!done) {
		int tag = input.readTag();
		switch (tag) {
		case 0:
		    done = true;
		    break;
		case 10: {
		    java.lang.String s = input.readStringRequireUtf8();

		    message_ = s;
		    break;
		}
		case 16: {

		    timestamp_ = input.readInt64();
		    break;
		}
		default: {
		    if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
			done = true;
		    }
		    break;
		}
		}
	    }
	} catch (com.google.protobuf.InvalidProtocolBufferException e) {
	    throw e.setUnfinishedMessage(this);
	} catch (java.io.IOException e) {
	    throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
	} finally {
	    this.unknownFields = unknownFields.build();
	    makeExtensionsImmutable();
	}
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
	return iml.ImlThrift.internal_static_TextMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
	return iml.ImlThrift.internal_static_TextMessage_fieldAccessorTable
		.ensureFieldAccessorsInitialized(iml.TextMessage.class, iml.TextMessage.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;

    /**
     * <code>string message = 1;</code>
     * 
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
	java.lang.Object ref = message_;
	if (ref instanceof java.lang.String) {
	    return (java.lang.String) ref;
	} else {
	    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
	    java.lang.String s = bs.toStringUtf8();
	    message_ = s;
	    return s;
	}
    }

    /**
     * <code>string message = 1;</code>
     * 
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMessageBytes() {
	java.lang.Object ref = message_;
	if (ref instanceof java.lang.String) {
	    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
	    message_ = b;
	    return b;
	} else {
	    return (com.google.protobuf.ByteString) ref;
	}
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;

    /**
     * <code>int64 timestamp = 2;</code>
     * 
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
	return timestamp_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
	byte isInitialized = memoizedIsInitialized;
	if (isInitialized == 1)
	    return true;
	if (isInitialized == 0)
	    return false;

	memoizedIsInitialized = 1;
	return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
	if (!getMessageBytes().isEmpty()) {
	    com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
	}
	if (timestamp_ != 0L) {
	    output.writeInt64(2, timestamp_);
	}
	unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
	int size = memoizedSize;
	if (size != -1)
	    return size;

	size = 0;
	if (!getMessageBytes().isEmpty()) {
	    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
	}
	if (timestamp_ != 0L) {
	    size += com.google.protobuf.CodedOutputStream.computeInt64Size(2, timestamp_);
	}
	size += unknownFields.getSerializedSize();
	memoizedSize = size;
	return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
	if (obj == this) {
	    return true;
	}
	if (!(obj instanceof iml.TextMessage)) {
	    return super.equals(obj);
	}
	iml.TextMessage other = (iml.TextMessage) obj;

	if (!getMessage().equals(other.getMessage()))
	    return false;
	if (getTimestamp() != other.getTimestamp())
	    return false;
	if (!unknownFields.equals(other.unknownFields))
	    return false;
	return true;
    }

    @java.lang.Override
    public int hashCode() {
	if (memoizedHashCode != 0) {
	    return memoizedHashCode;
	}
	int hash = 41;
	hash = (19 * hash) + getDescriptor().hashCode();
	hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
	hash = (53 * hash) + getMessage().hashCode();
	hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
	hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getTimestamp());
	hash = (29 * hash) + unknownFields.hashCode();
	memoizedHashCode = hash;
	return hash;
    }

    public static iml.TextMessage parseFrom(java.nio.ByteBuffer data)
	    throws com.google.protobuf.InvalidProtocolBufferException {
	return PARSER.parseFrom(data);
    }

    public static iml.TextMessage parseFrom(java.nio.ByteBuffer data,
	    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
	    throws com.google.protobuf.InvalidProtocolBufferException {
	return PARSER.parseFrom(data, extensionRegistry);
    }

    public static iml.TextMessage parseFrom(com.google.protobuf.ByteString data)
	    throws com.google.protobuf.InvalidProtocolBufferException {
	return PARSER.parseFrom(data);
    }

    public static iml.TextMessage parseFrom(com.google.protobuf.ByteString data,
	    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
	    throws com.google.protobuf.InvalidProtocolBufferException {
	return PARSER.parseFrom(data, extensionRegistry);
    }

    public static iml.TextMessage parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
	return PARSER.parseFrom(data);
    }

    public static iml.TextMessage parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
	    throws com.google.protobuf.InvalidProtocolBufferException {
	return PARSER.parseFrom(data, extensionRegistry);
    }

    public static iml.TextMessage parseFrom(java.io.InputStream input) throws java.io.IOException {
	return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static iml.TextMessage parseFrom(java.io.InputStream input,
	    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
	return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static iml.TextMessage parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
	return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static iml.TextMessage parseDelimitedFrom(java.io.InputStream input,
	    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
	return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static iml.TextMessage parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
	return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static iml.TextMessage parseFrom(com.google.protobuf.CodedInputStream input,
	    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
	return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
	return newBuilder();
    }

    public static Builder newBuilder() {
	return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(iml.TextMessage prototype) {
	return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
	return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
	Builder builder = new Builder(parent);
	return builder;
    }

    /**
     * Protobuf type {@code TextMessage}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
	    // @@protoc_insertion_point(builder_implements:TextMessage)
	    iml.TextMessageOrBuilder {
	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
	    return iml.ImlThrift.internal_static_TextMessage_descriptor;
	}

	@java.lang.Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
	    return iml.ImlThrift.internal_static_TextMessage_fieldAccessorTable
		    .ensureFieldAccessorsInitialized(iml.TextMessage.class, iml.TextMessage.Builder.class);
	}

	// Construct using iml.TextMessage.newBuilder()
	private Builder() {
	    maybeForceBuilderInitialization();
	}

	private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
	    super(parent);
	    maybeForceBuilderInitialization();
	}

	private void maybeForceBuilderInitialization() {
	    if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
	    }
	}

	@java.lang.Override
	public Builder clear() {
	    super.clear();
	    message_ = "";

	    timestamp_ = 0L;

	    return this;
	}

	@java.lang.Override
	public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
	    return iml.ImlThrift.internal_static_TextMessage_descriptor;
	}

	@java.lang.Override
	public iml.TextMessage getDefaultInstanceForType() {
	    return iml.TextMessage.getDefaultInstance();
	}

	@java.lang.Override
	public iml.TextMessage build() {
	    iml.TextMessage result = buildPartial();
	    if (!result.isInitialized()) {
		throw newUninitializedMessageException(result);
	    }
	    return result;
	}

	@java.lang.Override
	public iml.TextMessage buildPartial() {
	    iml.TextMessage result = new iml.TextMessage(this);
	    result.message_ = message_;
	    result.timestamp_ = timestamp_;
	    onBuilt();
	    return result;
	}

	@java.lang.Override
	public Builder clone() {
	    return super.clone();
	}

	@java.lang.Override
	public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
	    return super.setField(field, value);
	}

	@java.lang.Override
	public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
	    return super.clearField(field);
	}

	@java.lang.Override
	public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
	    return super.clearOneof(oneof);
	}

	@java.lang.Override
	public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
		java.lang.Object value) {
	    return super.setRepeatedField(field, index, value);
	}

	@java.lang.Override
	public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
	    return super.addRepeatedField(field, value);
	}

	@java.lang.Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
	    if (other instanceof iml.TextMessage) {
		return mergeFrom((iml.TextMessage) other);
	    } else {
		super.mergeFrom(other);
		return this;
	    }
	}

	public Builder mergeFrom(iml.TextMessage other) {
	    if (other == iml.TextMessage.getDefaultInstance())
		return this;
	    if (!other.getMessage().isEmpty()) {
		message_ = other.message_;
		onChanged();
	    }
	    if (other.getTimestamp() != 0L) {
		setTimestamp(other.getTimestamp());
	    }
	    this.mergeUnknownFields(other.unknownFields);
	    onChanged();
	    return this;
	}

	@java.lang.Override
	public final boolean isInitialized() {
	    return true;
	}

	@java.lang.Override
	public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
		com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
	    iml.TextMessage parsedMessage = null;
	    try {
		parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
	    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
		parsedMessage = (iml.TextMessage) e.getUnfinishedMessage();
		throw e.unwrapIOException();
	    } finally {
		if (parsedMessage != null) {
		    mergeFrom(parsedMessage);
		}
	    }
	    return this;
	}

	private java.lang.Object message_ = "";

	/**
	 * <code>string message = 1;</code>
	 * 
	 * @return The message.
	 */
	public java.lang.String getMessage() {
	    java.lang.Object ref = message_;
	    if (!(ref instanceof java.lang.String)) {
		com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
		java.lang.String s = bs.toStringUtf8();
		message_ = s;
		return s;
	    } else {
		return (java.lang.String) ref;
	    }
	}

	/**
	 * <code>string message = 1;</code>
	 * 
	 * @return The bytes for message.
	 */
	public com.google.protobuf.ByteString getMessageBytes() {
	    java.lang.Object ref = message_;
	    if (ref instanceof String) {
		com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
		message_ = b;
		return b;
	    } else {
		return (com.google.protobuf.ByteString) ref;
	    }
	}

	/**
	 * <code>string message = 1;</code>
	 * 
	 * @param value The message to set.
	 * @return This builder for chaining.
	 */
	public Builder setMessage(java.lang.String value) {
	    if (value == null) {
		throw new NullPointerException();
	    }

	    message_ = value;
	    onChanged();
	    return this;
	}

	/**
	 * <code>string message = 1;</code>
	 * 
	 * @return This builder for chaining.
	 */
	public Builder clearMessage() {

	    message_ = getDefaultInstance().getMessage();
	    onChanged();
	    return this;
	}

	/**
	 * <code>string message = 1;</code>
	 * 
	 * @param value The bytes for message to set.
	 * @return This builder for chaining.
	 */
	public Builder setMessageBytes(com.google.protobuf.ByteString value) {
	    if (value == null) {
		throw new NullPointerException();
	    }
	    checkByteStringIsUtf8(value);

	    message_ = value;
	    onChanged();
	    return this;
	}

	private long timestamp_;

	/**
	 * <code>int64 timestamp = 2;</code>
	 * 
	 * @return The timestamp.
	 */
	@java.lang.Override
	public long getTimestamp() {
	    return timestamp_;
	}

	/**
	 * <code>int64 timestamp = 2;</code>
	 * 
	 * @param value The timestamp to set.
	 * @return This builder for chaining.
	 */
	public Builder setTimestamp(long value) {

	    timestamp_ = value;
	    onChanged();
	    return this;
	}

	/**
	 * <code>int64 timestamp = 2;</code>
	 * 
	 * @return This builder for chaining.
	 */
	public Builder clearTimestamp() {

	    timestamp_ = 0L;
	    onChanged();
	    return this;
	}

	@java.lang.Override
	public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
	    return super.setUnknownFields(unknownFields);
	}

	@java.lang.Override
	public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
	    return super.mergeUnknownFields(unknownFields);
	}

	// @@protoc_insertion_point(builder_scope:TextMessage)
    }

    // @@protoc_insertion_point(class_scope:TextMessage)
    private static final iml.TextMessage DEFAULT_INSTANCE;
    static {
	DEFAULT_INSTANCE = new iml.TextMessage();
    }

    public static iml.TextMessage getDefaultInstance() {
	return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TextMessage> PARSER = new com.google.protobuf.AbstractParser<TextMessage>() {
	@java.lang.Override
	public TextMessage parsePartialFrom(com.google.protobuf.CodedInputStream input,
		com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		throws com.google.protobuf.InvalidProtocolBufferException {
	    return new TextMessage(input, extensionRegistry);
	}
    };

    public static com.google.protobuf.Parser<TextMessage> parser() {
	return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TextMessage> getParserForType() {
	return PARSER;
    }

    @java.lang.Override
    public iml.TextMessage getDefaultInstanceForType() {
	return DEFAULT_INSTANCE;
    }

}
